# Generated by Django 2.1.7 on 2021-06-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R64app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='receiver',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='receiver',
            new_name='reciever',
        ),
    ]
